spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
  datasource:
    url: jdbc:mysql://${DB_ADDR:localhost}:${DB_PORT:3306}/${DB_SCHEMA:spring-test}?serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:}